### ISSUE TITLE
incluir um .gitgnore pros arquivos que não tem relação com o projeto

### ISSUE THREAD

**Issue by samycici** [CS-Mateus-Miranda/ProjetoLojaIntegrada#1]

**Comment by Kirmayrtomaz** [comment]
O arquivo **.gitignore** tem que ser adicionado na raiz do diretório. 
dentro dele basta vc colocar os diretórios e arquivos que não deseja comitar no projeto.

`.gitignore`
dentro dele colocar como exemplo

`node_modules/`
`.vscode/`
